server:
  port: 8082
  servlet:
    context-path: /hello-world-new

spring:
  cache:
    type: ehcache
    config: classpath:ehcache.xml
#  datasource:
#    url:
#    username:
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/Users/XuesongBu/Documents/git_code/hello-world/hello-world.db
    username:
    password:
  #针对SQLite配置方言，MySQL不需要该配置
  jpa:
    database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect
  #RabbitMQ服务器配置，地址账号密码，virtualhost等配置
  rabbitmq:
    addresses:
    username:
    password:
    virtual-host: