server:
  port: 8082
  servlet:
    context-path: /test-mybatis-flex

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    # 配置你自己的  sqlite db 文件路径
    url: jdbc:sqlite:/Users/buxuesong/Documents/git_code/hello-world/hello-world.db
    username:
    password:

